#!/bin/sh

# manuel en modifiant le $HOME si besoin
sudo find /$HOME -name ".DS_Store" -depth -exec rm {} \;

##############################################

# auto methode 1 
sudo crontab -e
# echo "15 19 * * * root find /$HOME -name \".DS_Store\" -depth -exec rm {} \\;" | sudo tee -a /etc/crontab > /dev/null

# appuyer sur "i" et coller le texte suivant en modifiant le $HOME si besoin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
 15 19  *  *  * root find /$HOME -name ".DS_Store" -depth -exec rm {} \; 

# ensuite appuyer sur "echap" et ":wq"

##############################################

# auto methode 2
env EDITOR=nano crontab -e

#coller le texte suivant en modifiant le $HOME si besoin

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
 15 19  *  *  * root find /$HOME -name ".DS_Store" -depth -exec rm {} \; 

 # "ctrl + o" "enter" "ctrl + x"
