# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: MOTDEPASSE
    ports:
      - 3306:3306
    volumes:
      - /$HOME/docker/mariadb/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080