version: '3.3'

services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    volumes:
      - /$HOME/docker/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  default:
    name: npmproxy
    external: true